### ISSUE TITLE
axios example: The provided value 'stream' is not a valid enum value of type XMLHttpRequestResponseType.

### ISSUE THREAD

**Issue by marcelobbfonseca** [andrewstart/axios-streaming#1]
I'm getting the following warning when i try to make the request using axios example. 

![sswarningcrop](https://user-images.githubusercontent.com/15076350/47449733-bca99a80-d799-11e8-96b2-8bb8707a5783.jpg)

The request also never ends. I made the stream with a django backend and I want to display the video stream in my Vue-Cli frontend with axios request

**Comment by andrewstart** [comment]
Is your front end being run in Electron (or another combination of Node and a browser)?

**Comment by marcelobbfonseca** [comment]
I'm using webpack. Does that count?

**Comment by andrewstart** [comment]
That does not. This example is specifically about using Node's binary stream APIs, so the browser native version of Axios won't support Node streams.

**Comment by marcelobbfonseca** [comment]
ok, thanks for the quick reply

**Comment by dae54** [comment]
> Is your front end being run in Electron (or another combination of Node and a browser)?

I am using Electron, and experience that error, what should i do? Actually i am downloading a video from a nodejs server to react-electron client app

**Comment by andrewstart** [comment]
Electron has the ability to prevent the renderer process from using node, leaving it as a standard browser only process. Either use the browser version of axios, or enable node in your renderer process. Beyond that, I don't have any ideas, as I haven't touched this in years.
